version: "3"

networks:
  blockchain.ciag:
    external:
      name: net_condominio

services:
  fluentd:
    container_name: fluentd
    build:
      context: .
    user: root
    image: fluentd
    volumes:
      - /var/lib/docker/containers:/fluentd/log/containers # Example: Reading docker logs
      - ./:/fluentd/etc/
      - ./logs:/output/ # Example: Fluentd will collect logs and store it here for demo
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - blockchain.ciag

  elasticsearch: # port 9200
    image: elasticsearch:7.9.1
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - http.cors.enabled=true
      - http.cors.allow-origin="*"
      - cluster.initial_master_nodes=elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - transport.host=127.0.0.1
      - http.host=0.0.0.0
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - blockchain.ciag
  kibana:
    image: kibana:7.9.1
    container_name: kibana
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    networks:
      - blockchain.ciag
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
