# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: "2"

volumes:
  orderer0.montadora.ciag:
  orderer1.montadora.ciag:
  orderer2.montadora.ciag:
  peer0.montadora.ciag:
  peer1.montadora.ciag:
  peer2.montadora.ciag:
  peer0.sistemista.ciag:
  peer1.sistemista.ciag:
  peer2.sistemista.ciag:

networks:
  condominio:

services:
  orderer0.montadora.ciag:
    container_name: orderer0.montadora.ciag
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    environment:
      - ORDERER_OPERATIONS_LISTENADDRESS=orderer0.montadora.ciag:9443
      - ORDERER_METRICS_PROVIDER=prometheus
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=6130
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1
      - ORDERER_KAFKA_VERBOSE=true
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - ../system-genesis-block/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ../organizations/ordererOrganizations/montadora.ciag/orderers/orderer0.montadora.ciag/msp:/var/hyperledger/orderer/msp
      - ../organizations/ordererOrganizations/montadora.ciag/orderers/orderer0.montadora.ciag/tls/:/var/hyperledger/orderer/tls
      - orderer0.montadora.ciag:/var/hyperledger/production/orderer
    ports:
      - 6130:6130
      - 6145:9443
    networks:
      - condominio

  orderer1.montadora.ciag:
    container_name: orderer1.montadora.ciag
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    environment:
      - ORDERER_OPERATIONS_LISTENADDRESS=orderer1.montadora.ciag:9443
      - ORDERER_METRICS_PROVIDER=prometheus
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=6230
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1
      - ORDERER_KAFKA_VERBOSE=true
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - ../system-genesis-block/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ../organizations/ordererOrganizations/montadora.ciag/orderers/orderer1.montadora.ciag/msp:/var/hyperledger/orderer/msp
      - ../organizations/ordererOrganizations/montadora.ciag/orderers/orderer1.montadora.ciag/tls/:/var/hyperledger/orderer/tls
      - orderer1.montadora.ciag:/var/hyperledger/production/orderer
    ports:
      - 6230:6230
      - 6245:9443
    networks:
      - condominio
    depends_on:
      - orderer0.montadora.ciag

  orderer2.montadora.ciag:
    container_name: orderer2.montadora.ciag
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    environment:
      - ORDERER_OPERATIONS_LISTENADDRESS=orderer2.montadora.ciag:9443
      - ORDERER_METRICS_PROVIDER=prometheus
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=6330
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1
      - ORDERER_KAFKA_VERBOSE=true
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - ../system-genesis-block/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ../organizations/ordererOrganizations/montadora.ciag/orderers/orderer2.montadora.ciag/msp:/var/hyperledger/orderer/msp
      - ../organizations/ordererOrganizations/montadora.ciag/orderers/orderer2.montadora.ciag/tls/:/var/hyperledger/orderer/tls
      - orderer2.montadora.ciag:/var/hyperledger/production/orderer
    ports:
      - 6330:6330
      - 6345:9443
    networks:
      - condominio
    depends_on:
      - orderer0.montadora.ciag

  peer0.montadora.ciag:
    container_name: peer0.montadora.ciag
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      - CORE_VM_DOCKER_ATTACHSTDOUT=true
      - CORE_OPERATIONS_LISTENADDRESS=peer0.montadora.ciag:9444
      - CORE_METRICS_PROVIDER=prometheus
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_condominio
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variabes
      - CORE_PEER_ID=peer0.montadora.ciag
      - CORE_PEER_ADDRESS=peer0.montadora.ciag:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.montadora.ciag:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.montadora.ciag:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.montadora.ciag:7051
      - CORE_PEER_LOCALMSPID=MontadoraMSP
    volumes:
      - /var/run/:/host/var/run/
      - ../organizations/peerOrganizations/montadora.ciag/peers/peer0.montadora.ciag/msp:/etc/hyperledger/fabric/msp
      - ../organizations/peerOrganizations/montadora.ciag/peers/peer0.montadora.ciag/tls:/etc/hyperledger/fabric/tls
      - peer0.montadora.ciag:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 7051:7051
      - 9444:9444
    networks:
      - condominio

  peer1.montadora.ciag:
    container_name: peer1.montadora.ciag
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      - CORE_VM_DOCKER_ATTACHSTDOUT=true
      - CORE_OPERATIONS_LISTENADDRESS=peer1.montadora.ciag:9544
      - CORE_METRICS_PROVIDER=prometheus
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_condominio
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variabes
      - CORE_PEER_ID=peer1.montadora.ciag
      - CORE_PEER_ADDRESS=peer1.montadora.ciag:7151
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7151
      - CORE_PEER_CHAINCODEADDRESS=peer1.montadora.ciag:7152
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7152
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.montadora.ciag:7151
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.montadora.ciag:7151
      - CORE_PEER_LOCALMSPID=MontadoraMSP
    volumes:
      - /var/run/:/host/var/run/
      - ../organizations/peerOrganizations/montadora.ciag/peers/peer1.montadora.ciag/msp:/etc/hyperledger/fabric/msp
      - ../organizations/peerOrganizations/montadora.ciag/peers/peer1.montadora.ciag/tls:/etc/hyperledger/fabric/tls
      - peer1.montadora.ciag:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 7151:7151
      - 9544:9544
    networks:
      - condominio

  peer2.montadora.ciag:
    container_name: peer2.montadora.ciag
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      - CORE_VM_DOCKER_ATTACHSTDOUT=true
      - CORE_OPERATIONS_LISTENADDRESS=peer2.montadora.ciag:9644
      - CORE_METRICS_PROVIDER=prometheus
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_condominio
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variabes
      - CORE_PEER_ID=peer2.montadora.ciag
      - CORE_PEER_ADDRESS=peer2.montadora.ciag:7251
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7251
      - CORE_PEER_CHAINCODEADDRESS=peer2.montadora.ciag:7252
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7252
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer2.montadora.ciag:7251
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer2.montadora.ciag:7251
      - CORE_PEER_LOCALMSPID=MontadoraMSP
    volumes:
      - /var/run/:/host/var/run/
      - ../organizations/peerOrganizations/montadora.ciag/peers/peer2.montadora.ciag/msp:/etc/hyperledger/fabric/msp
      - ../organizations/peerOrganizations/montadora.ciag/peers/peer2.montadora.ciag/tls:/etc/hyperledger/fabric/tls
      - peer2.montadora.ciag:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 7251:7251
      - 9644:9644
    networks:
      - condominio

  peer0.sistemista.ciag:
    container_name: peer0.sistemista.ciag
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      - CORE_VM_DOCKER_ATTACHSTDOUT=true
      - CORE_OPERATIONS_LISTENADDRESS=peer0.sistemista.ciag:9445
      - CORE_METRICS_PROVIDER=prometheus
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_condominio
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variabes
      - CORE_PEER_ID=peer0.sistemista.ciag
      - CORE_PEER_ADDRESS=peer0.sistemista.ciag:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.sistemista.ciag:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.sistemista.ciag:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.sistemista.ciag:9051
      - CORE_PEER_LOCALMSPID=SistemistaMSP
    volumes:
      - /var/run/:/host/var/run/
      - ../organizations/peerOrganizations/sistemista.ciag/peers/peer0.sistemista.ciag/msp:/etc/hyperledger/fabric/msp
      - ../organizations/peerOrganizations/sistemista.ciag/peers/peer0.sistemista.ciag/tls:/etc/hyperledger/fabric/tls
      - peer0.sistemista.ciag:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 9051:9051
      - 9445:9445
    networks:
      - condominio

  peer1.sistemista.ciag:
    container_name: peer1.sistemista.ciag
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      - CORE_VM_DOCKER_ATTACHSTDOUT=true
      - CORE_OPERATIONS_LISTENADDRESS=peer1.sistemista.ciag:9545
      - CORE_METRICS_PROVIDER=prometheus
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_condominio
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variabes
      - CORE_PEER_ID=peer1.sistemista.ciag
      - CORE_PEER_ADDRESS=peer1.sistemista.ciag:9151
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9151
      - CORE_PEER_CHAINCODEADDRESS=peer1.sistemista.ciag:9152
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9152
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.sistemista.ciag:9151
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.sistemista.ciag:9151
      - CORE_PEER_LOCALMSPID=SistemistaMSP
    volumes:
      - /var/run/:/host/var/run/
      - ../organizations/peerOrganizations/sistemista.ciag/peers/peer1.sistemista.ciag/msp:/etc/hyperledger/fabric/msp
      - ../organizations/peerOrganizations/sistemista.ciag/peers/peer1.sistemista.ciag/tls:/etc/hyperledger/fabric/tls
      - peer1.sistemista.ciag:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 9151:9151
      - 9545:9545
    networks:
      - condominio

  peer2.sistemista.ciag:
    container_name: peer2.sistemista.ciag
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      - CORE_VM_DOCKER_ATTACHSTDOUT=true
      - CORE_OPERATIONS_LISTENADDRESS=peer2.sistemista.ciag:9645
      - CORE_METRICS_PROVIDER=prometheus
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_condominio
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variabes
      - CORE_PEER_ID=peer2.sistemista.ciag
      - CORE_PEER_ADDRESS=peer2.sistemista.ciag:9251
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9251
      - CORE_PEER_CHAINCODEADDRESS=peer2.sistemista.ciag:9252
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9252
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer2.sistemista.ciag:9251
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer2.sistemista.ciag:9251
      - CORE_PEER_LOCALMSPID=SistemistaMSP
    volumes:
      - /var/run/:/host/var/run/
      - ../organizations/peerOrganizations/sistemista.ciag/peers/peer2.sistemista.ciag/msp:/etc/hyperledger/fabric/msp
      - ../organizations/peerOrganizations/sistemista.ciag/peers/peer2.sistemista.ciag/tls:/etc/hyperledger/fabric/tls
      - peer2.sistemista.ciag:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 9251:9251
      - 9645:9645
    networks:
      - condominio
